### ISSUE TITLE
Collision can push ball out of reflecting border

### ISSUE THREAD

**Issue by muedli** [phetsims/collision-lab#171]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.15.5

<b>Browser</b>

Chrome 85.0.4183.102

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/537. I've found a way that you can hit a ball that pushes it out of the reflecting border. Maybe related to https://github.com/phetsims/collision-lab/issues/167? See the gif below.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/60749003/93160991-d6766280-f6ce-11ea-8d83-48a00ae87556.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.2/phet/collision-lab_en_phet.html
Version: 1.1.0-dev.2 2020-08-21 16:28:07 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Language: en-US
Window: 1440x798
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by brandonLi8** [comment]
Doesn't look like it's related to #167. Definitely looks to be related to https://github.com/phetsims/collision-lab/issues/132.

**Comment by jonathanolson** [comment]
When trying to reproduce this, I'm noticing that balls in the inelastic screen seem to be getting "stuck" at one another:

![image](https://user-images.githubusercontent.com/480878/94294516-2e0d9d00-ff1d-11ea-8473-9b00dd1f2941.png)

**Comment by jonathanolson** [comment]
Reproducing with "slip" and the preset:

```js
  DEBUG: new InelasticPresetValue( [
    new BallState( new Vector2( 1.84, 0.84 ), new Vector2( 1, 0.3 ), 0.5 ),
    new BallState( new Vector2( 0.03, -0.16 ), new Vector2( 1.57, 0.73 ), 1.5 )
  ] )
```

**Comment by jonathanolson** [comment]
I'll have some incoming bug fixes soon for what I was able to reproduce, there were some regressions that I've fixed up.

**Comment by jonathanolson** [comment]
After fixing things that prevented me from testing this, I screen-shotted the video and used this case to try to reproduce:
```js
  DEBUG: new InelasticPresetValue( [
    new BallState( new Vector2( 0.82, 0.12 ), new Vector2( 2.82, 1.83 ), 0.5 ),
    new BallState( new Vector2( 1.8, 0.8 ), new Vector2( 0, 0 ), 0.5 )
  ] )
```

In master now, it behaves as normal, so I believe this should be fixed.

**Comment by KatieWoe** [comment]
This seems like it still occurs in https://github.com/phetsims/collision-lab/issues/178. @jonathanolson Let me know if you want me to close one of these as a duplicate.

**Comment by KatieWoe** [comment]
Looking closer, I think they may be different actually.

**Comment by KatieWoe** [comment]
Have not been able to reproduce this myself in dev.10

**Comment by KatieWoe** [comment]
Looks fixed both in regards to escaped ball and https://github.com/phetsims/collision-lab/issues/171#issuecomment-699037876. I tried one or two other configurations and it didn't happen there. Will reopen if something similar returns.
